services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: match-my-movie
      POSTGRES_PASSWORD: match-my-movie-pw
      POSTGRES_DB: match-my-movie
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
